petapp1/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import search_view, ProceedToPaymentView, PaymentSuccessView, OrderSummaryView, CreateOrderView, RemoveFromCartView, AddToCartView, CartView, CustomLoginView, ProductUpdateView, ProductDeleteView, contact_submit_page, privacypolicypage, termspage, faqpage, aboutpage, contactpage, UserCreateView, PetUserList , PetList, PetCreateView, PetDetailView, PetUpdateView, PetDeleteView, homepage, ProductList, ProductCreateView, ProductDetailView

urlpatterns = [
    path('home/', homepage, name='home'),
    path('about/', aboutpage, name='about'),
    path('contact/', contactpage, name='contact'),
    path('contact_submit/', contact_submit_page, name="contact_submit"),
    path('privacy_policy/', privacypolicypage, name='privacy_policy'),
    path('terms/', termspage, name='terms'),
    path('faq/', faqpage, name='faq'),
    path('search/', search_view, name='search'),
    path('login/', CustomLoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name="logout"),
    path('create_user/', UserCreateView, name="create_user"),
    path('petuser_list/', PetUserList.as_view(), name="petuser_list"),
    path('pet_list/', PetList.as_view(), name="pet_list"),
    path('create_pet/', PetCreateView.as_view(), name="create_pet"),
    path('pet_detail_view/<int:pk>', PetDetailView.as_view(), name="pet_detail_view"),
    path('update_pet/<int:pk>', PetUpdateView.as_view(), name="update_pet"),
    path('delete_pet/<int:pk>', PetDeleteView.as_view(), name="delete_pet"),
    path('product_list/', ProductList.as_view(), name="product_list"),
    path('create_product/', ProductCreateView.as_view(), name="create_product"),
    path('product_detail_view/<int:pk>', ProductDetailView.as_view(), name="product_detail_view"),
    path('update_product/<int:pk>', ProductUpdateView.as_view(), name="update_product"),
    path('delete_product/<int:pk>', ProductDeleteView.as_view(), name="delete_product"),
    path('add_to_cart/',AddToCartView.as_view(), name="add_to_cart"),
    path('remove_from_cart/<int:cart_id>/', RemoveFromCartView.as_view(), name="remove_from_cart"),
    path('view_cart/', CartView.as_view(), name="view_cart"),
    path('create_order/', CreateOrderView.as_view(), name="create_order"),
    path('order_summary/<int:order_id>/', OrderSummaryView.as_view(), name="order_summary"),
    path('order/<int:order_id>/payment/', ProceedToPaymentView.as_view(), name='proceed_to_payment'),
    path('order/<int:order_id>/payment-success/', PaymentSuccessView.as_view(), name='payment_success'),
]

petapp1/models.py
#from tkinter import CASCADE
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.contrib.auth.models import AbstractUser

# Create your models here.
class PetUser(AbstractUser):
    fname = models.CharField(max_length=30)
    lname = models.CharField(max_length=30)
    email1 = models.CharField(max_length=50)
    phone1 = models.CharField(max_length=14)
    address1 = models.CharField(max_length=100)

    def __str__(self):
        return self.username


class PetManager(models.Manager):
    def search(self, query):
        if query: 
            return self.get_queryset().filter(models.Q(name__exact=query)|models.Q(breed__exact=query))


class Pet(models.Model):
    name = models.CharField(max_length=20, validators=[RegexValidator(regex=r'^[a-zA-Z\s]+$', message=("Name can contain only alphabets and spaces"), code="invalid_name")])
    breed = models.CharField(max_length=30,)
    age = models.IntegerField(validators=[MinValueValidator(1, message=("The minimun age value for pet is 1 years")), MaxValueValidator(15, message=("The maximum age for pet is 15 years."))])
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(10000, message=("The minimum priced pet should be 10000 rupees."))])
    type = models.CharField(max_length=10)
    description = models.CharField(max_length=100)
    image = models.ImageField(upload_to='pet_images/', blank=True, null=True)

    objects = PetManager()

    # adding certain permission 
    class Meta:
        permissions = [
            ('can_add_pet', 'Can add a pet'), 
            ('can_update_pet', 'Can update a pet')
        ]

class Product(models.Model):
    product_name = models.CharField(max_length=20, validators=[RegexValidator(regex=r'^[a-zA-Z\s]+$', message=("Product Name can contain only alphabets and spaces"), code="invalid_product_name")])
    category = models.CharField(max_length=15)
    price = models.DecimalField(max_digits=10, decimal_places=2,validators=[MinValueValidator(1000, message=("The minimum priced pet product should be 1000 rupees."))] )
    quantity_in_stock = models.IntegerField()
    description = models.CharField(max_length=100)
    image = models.ImageField(upload_to='product_images/')

class Order(models.Model):
    user_id = models.ForeignKey(PetUser, on_delete=models.CASCADE)
    order_date = models.DateTimeField()
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    PAYMENT_STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('COMPLETED', 'Completed'),
        ('FAILED', 'Failed'),
    ]
    payment_status = models.CharField(
        max_length=10, choices=PAYMENT_STATUS_CHOICES, default='PENDING'
    )
    razorpay_payment_id = models.CharField(max_length=100, blank=True, null=True)

class OrderItem(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    pet_id = models.ForeignKey(Pet, on_delete=models.CASCADE, blank=True, null=True)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

class Cart(models.Model):
    customer_id = models.ForeignKey(PetUser, on_delete=models.CASCADE)
    pet_id = models.ForeignKey(Pet, on_delete=models.CASCADE, null=True, blank=True)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField()
    date_added = models.DateTimeField()

class Payments(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment_date = models.DateTimeField()
    payment_method = models.CharField(max_length=15)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.email}"

petapp1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import PetUser, Pet, Product, Contact
from django.contrib.auth.forms import AuthenticationForm

class CustomAuthenticationForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False, label="Remember Me")

class PetUserForm(UserCreationForm):
    class Meta:
        model = PetUser
        fields = ['username', 'fname', 'lname', 'email1', 'phone1', 'address1', 'password1', 'password2']
    
    def __init__(self, *args, **kwargs):
        super(PetUserForm, self).__init__(*args, **kwargs)
        
        # Apply max_length and Bootstrap classes to all fields
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})
        
        # Explicitly set max_length for password fields
        self.fields['password1'].widget.attrs.update({'maxlength': '100'})
        self.fields['password2'].widget.attrs.update({'maxlength': '100'})

class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'breed', 'age', 'price', 'type', 'description', 'image']        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'breed': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'type': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            
        }

    def __init__(self, *args, **kwargs):
        super(PetForm, self).__init__(*args, **kwargs)

        # Explicitly styling the ImageField
        self.fields['image'].widget.attrs.update({'class': 'form-control'})
        
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'category', 'price', 'quantity_in_stock', 'description', 'image']        
        widgets = {
            'product_name': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'quantity_in_stock': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            
        }

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        # Explicitly styling the ImageField
        self.fields['image'].widget.attrs.update({'class': 'form-control'})

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.TextInput(attrs={'class': 'form-control'}),
            
        }

petapp1/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <h2 class="text-center">About Us</h2>
        <p class="lead text-center">
            Welcome to our Pet Store! We are passionate about providing the best care and products for pets. Our store offers a wide variety of pets, pet supplies, and accessories, tailored to meet the needs of both pets and their owners.
        </p>
        
        <h3 class="mt-4">Our Mission</h3>
        <p>
            Our mission is to provide high-quality pets and pet products to ensure that your pet lives a long and healthy life. We aim to create a welcoming and educational environment for pet owners, offering expert advice and guidance on pet care.
        </p>
        
        <h3 class="mt-4">Why Choose Us?</h3>
        <ul>
            <li>Wide variety of pets from trusted breeders</li>
            <li>High-quality pet food and accessories</li>
            <li>Expert advice and pet care services</li>
            <li>Committed to animal welfare</li>
        </ul>

        <h3 class="mt-4">Our Team</h3>
        <p>
            We are a team of pet lovers who believe that pets are part of the family. Our staff includes knowledgeable pet care professionals, animal behaviorists, and pet trainers who are ready to assist you with all your pet-related needs.
        </p>

        <h3 class="mt-4">Our Location</h3>
        <p>
            Visit us at our store, conveniently located in the heart of the city. We are open seven days a week and are always ready to help you find the perfect pet or pet product.
        </p>
    </div>
{% endblock %}

petapp1/templates/base.html
{% load static %}
<!doctype html>
<html>
	<head>
        <meta name="viewport" content="width= device-width, initial-scale= 1.0">
		<title>Home</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
       
    </head>

	<body>
        
        <nav class="navbar navbar-light navbar-expand-lg" style="background-color: rgb(56, 5, 5);">
            <div class="container">
                <a class="navbar-brand text-white" href="#">Pet Store</a>
                <button type="button" class="navbar-toggler" data-target="#navbarNav" 
                data-toggle="collapse" aria-controls="navbarNav" aria-expanded="false">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'about' %}" class="text-white">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'contact' %}" class="text-white">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'pet_list' %}">Pets</a> <!-- Link to Pet List -->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'product_list' %}">Products</a> <!-- Link to Product List -->
                    </li>
                    {% if user.is_staff %}
                    <!-- Admin links -->
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'create_pet' %}">Create Pet</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'create_product' %}">Create Product</a>
                    </li>
                    <li>
                        <a class="nav-link text-white" href="{% url 'create_user' %}">Create User</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <span class="nav-link text-white">Hello, {{ user.username }}!</span>
                            <form class="form" action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-primary mr-3" type="submit">Logout</button>
                            </form>   
                        {% else %}
                            <a class="nav-link text-white mr-3" href="{% url 'login' %}">Login</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link text-white" href="{% url 'view_cart' %}">
                                <i class="bi bi-cart"></i>
                                Cart ({{ cart_items_count }})
                            </a>
                        {% else %}
                            <a class="nav-link text-white" href="{% url 'view_cart' %}">
                                <i class="bi bi-cart"></i>
                                Cart (0)
                            </a>
                        {% endif %}
                    </li>
                    
                </ul>
                <form action="{% url 'search' %}" method="get" class="form-inline">
                    <input type="search" name="q" class="form-control mr-3"/>
                    <button type="submit" class="btn btn-outline-primary">Search</button>
                </form>
                </div>
            </div>
        </nav>

        <div class="container mt-3 text-center">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="footer-custom text-white py-4" style="background-color: rgb(56, 5, 5);">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <h5>Quick Links</h5>
                        <ul class="list-unstyled">
                            <li><a href="{% url 'home' %}" class="text-white">Home</a></li>
                            <li><a href="{% url 'pet_list' %}" class="text-white">Pets</a></li>
                            <li><a href="{% url 'about' %}" class="text-white">About Us</a></li>
                            <li><a href="{% url 'contact' %}" class="text-white">Contact</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h5>Customer Service</h5>
                        <ul class="list-unstyled">
                            <li><a href="{% url 'privacy_policy' %}" class="text-white">Privacy Policy</a></li>
                            <li><a href="{% url 'terms' %}" class="text-white">Terms of Service</a></li>
                            <li><a href="{% url 'faq' %}" class="text-white">FAQ</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h5>Follow Us</h5>
                        <ul class="list-unstyled">
                            <li><a href="https://facebook.com" class="text-white">Facebook</a></li>
                            <li><a href="https://twitter.com" class="text-white">Twitter</a></li>
                            <li><a href="https://instagram.com" class="text-white">Instagram</a></li>
                            <li><a href="https://youtube.com" class="text-white">YouTube</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h5>Contact Us</h5>
                        <ul class="list-unstyled">
                            <li>Email: <a href="mailto:info@petstore.com" class="text-white">info@petstore.com</a></li>
                            <li>Phone: <a href="tel:+1234567890" class="text-white">+1 234 567 890</a></li>
                        </ul>
                    </div>
                </div>
                <div class="text-center mt-4">
                    <p>&copy; 2024 Petstore Project | All Rights Reserved</p>
                </div>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

	</body>
</html>

petapp1/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart_items %}
            <tr>
                <td>
                    {% if item.pet_id %}
                    {{ item.pet_id.name }}
                    {% elif item.product_id %}
                    {{ item.product_id.product_name}}
                    {% endif %}
                   
                </td>
                <td>
                    {{ item.quantity }}
                </td>
                <td>
                    {% if item.pet_id %}
                    {{ item.pet_id.price }}
                    {% elif item.product_id %}
                    {{ item.product_id.price}}
                    {% endif %}
                </td>
                <td>
                    <form action="{% url 'remove_from_cart' item.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Remove</button>
                    </form>
                </td>
                <td>
                    <form action="{% url 'create_order' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Proceed to Checkout</button>
                    </form>
                </td>
            </tr>

            {% endfor %}
        </tbody>
    </table>
{% endblock %}

petapp1/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3 text-center">
    <div id="dogCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#dogCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#dogCarousel" data-slide-to="1"></li>
            <li data-target="#dogCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images/dog1-online.jpg' %}" class="d-block w-100" alt="Dog 1">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/dog2-online.webp' %}" class="d-block w-100" alt="Dog 2">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/dog3-online.webp' %}" class="d-block w-100" alt="Dog 3">
            </div>
        </div>
        <a class="carousel-control-prev" href="#dogCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#dogCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <!-- Content About Dogs -->
    <div class="container mt-5 text-center">
        <h2>About Dogs</h2>
        <p>Dogs are loyal and loving companions to millions of people worldwide. Known for their intelligence, bravery, and ability to connect with humans, dogs have served as pets, workers, and friends throughout history.</p>
        <p>From small breeds like the Chihuahua to larger breeds like the Golden Retriever, there is a dog for every family and lifestyle. At our pet store, we offer a wide variety of dog breeds, each with their own unique qualities.</p>
        <a href="{% url 'pet_list' %}" class="btn btn-primary mb-5">Browse Our Dogs</a>
    </div>
</div>
{% endblock %}

petapp1/templates/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5 mb-3">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header text-center bg-dark text-white">
                        <h4>Login to Your Account</h4>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.username.label_tag }} 
                                {{ form.username|add_class:"form-control" }}
                            </div>
                            <div class="form-group">
                                {{ form.password.label_tag }} 
                                {{ form.password|add_class:"form-control" }}
                            </div>
                            <div class="form-group form-check">
                                {{ form.remember_me }}
                                <label for="id_remember_me">Remember Me</label>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Login</button>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

petapp1/templates/order_summary.html
{% extends 'base.html' %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Type</th>
                <th>Quantity</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.orderitem_set.all %}
            <tr>
                <td>
                    {% if item.pet_id %}
                    {{ item.pet_id.name }}
                    {% elif item.product_id %}
                    {{ item.product_id.product_name}}
                    {% endif %}
                   
                </td>
                <td>
                    {% if item.pet_id %}
                    Pet
                    {% elif item.product_id %}
                    Product
                    {% endif %}
                   
                </td>
                <td>
                    {{ item.quantity }}
                </td>
                <td>
                    {{ item.price }}
                </td>   
            </tr>
            {% endfor %}

        </tbody>
        <a href="{% url 'proceed_to_payment' order.id %}" class="btn btn-success">Proceed to Payment</a>

    </table>
{% endblock %}

petapp1/templates/payment_success.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Payment Successful</h2>
    <p>Order ID: {{ order.id }}</p>
    <p>Total Amount: {{ order.total_amount }}</p>
    <p>Thank you for your purchase!</p>
    <a href="{% url 'home' %}" class="btn btn-primary">Go to Home</a>
</div>
{% endblock %}

petapp1/templates/pet_update_form.html
{% extends 'base.html' %}
{% block content%}
        <h2>Update a Pet</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Edit</button>
        </form>
{% endblock %}

petapp1/templates/petuser_list.html
{% extends 'base.html' %}
{% block content%}
<table class="table table-bordered table-striped">
    <tr>
    <thead>
        <th>First Name</th>
        <th>Last Name</th>
        <th>User Name</th>
        <th>Email</th>
        <th>Phone No.</th>
        <th>Address</th>
    </thead>
    </tr>
    <tbody> 
    {% for user in users %}
      
            <tr>
            <td> {{ user.fname }} </td> 
            <td>{{ user.lname }}</td> 
            <td> {{ user.username }} </td>
            <td> {{ user.email1 }} </td> 
            <td> {{ user.phone1 }} </td>
            <td> {{ user.address1 }} </td> 
            </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

petapp1/templates/product_list.html
{% extends 'base.html' %}
{% block content%}
<table class="table table-bordered table-striped">
    <tr>
    <thead>
        <th>Name</th>
        <th>Category</th>
        <th>Price</th>
        <th>Quantity in Stock</th>
        <th>Description</th>
    </thead>
    </tr>
    <tbody> 
    {% for product in products %}
      
            <tr>
            <td><a href="{% url 'product_detail_view' product.id %}"> {{ product.product_name }} </a></td> 
            <td>{{ product.category }}</td> 
            <td> {{ product.price }} </td>
            <td> {{ product.quantity_in_stock }} </td> 
            <td> {{ product.description }} </td>
            </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

petapp1/templates/product_update_form.html
{% extends 'base.html' %}
{% block content%}
        <h2>Update a Product</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Edit</button>
        </form>
{% endblock %}

petapp1/templates/search_results.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% if query %}
        <p>
            The searched data : {{ query }}
        </p>
        <p>
            The pet information : 
            <br>
            {% for pet in pet_manager %}
            Pet Name : {{ pet.name }}
            Pet Age : {{ pet.age }}
            Pet Breed : {{ pet.breed }}
            Pet Price : {{ pet.price }}
            {% endfor %}
        </p>
    {% endif %}
{% endblock %}

petapp1/templates/user_create_form.html
{% extends 'base.html' %}
{% block content%}
        <form method="post">
            {% csrf_token %}

                <div class="form-group">
                    {{ pet_user_form.username.label_tag }} {{ pet_user_form.username }}
                </div>
                <div class="form-group">
                    {{ pet_user_form.fname.label_tag }} {{ pet_user_form.fname }}
                </div>
                <div class="form-group">
                    {{ pet_user_form.lname.label_tag }} {{ pet_user_form.lname }}
                </div>
                <div class="form-group">
                    {{ pet_user_form.email1.label_tag }} {{ pet_user_form.email1 }}
                </div>
                <div class="form-group">
                    {{ pet_user_form.phone1.label_tag }} {{ pet_user_form.phone1 }}
                </div>
                <div class="form-group">
                    {{ pet_user_form.address1.label_tag }} {{ pet_user_form.address1 }}
                </div>
                <div class="form-group">
                    {{ pet_user_form.password1.label_tag }} {{ pet_user_form.password1 }}
                </div>
                <div class="form-group">
                    {{ pet_user_form.password2.label_tag }} {{ pet_user_form.password2 }}
                </div>
                <button type="submit" class="btn btn-primary m-2">Add Pet User</button>
        </form>
{% endblock %}